# Generated by Django 3.2.23 on 2024-02-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/media/placeholder.jpg', null=True, upload_to=''),
        ),
    ]
