# Generated by Django 3.2.23 on 2024-02-03 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_product_wishlist'),
        ('checkout', '0004_order_user_profile'),
        ('reviews', '0002_alter_review_reviewer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.order'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer_name', 'product')},
        ),
    ]
