# Generated by Django 3.2.23 on 2024-02-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Product Inquiry', 'Product Inquiry'), ('Feedback', 'Feedback'), ('Other', 'Other')], default='General Inquiry', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
