# Generated by Django 3.2.23 on 2024-01-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240130_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clearance',
            field=models.BooleanField(default=False),
        ),
    ]
