# Generated by Django 3.2.23 on 2024-02-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20240205_1319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiftAnswer',
        ),
        migrations.DeleteModel(
            name='GiftQuestion',
        ),
    ]
